// @format

'use strict';

const debug = require('debug')('cogs:areFiguresAbleToReachEachOther');
const PF = require('pathfinding');
const _ = require('lodash');

module.exports = () => {
  return (req, res, next) => {
    (function init() {
      debug(
        '// Checks if parcel generated by landGenerateMapPost fullfills condition so figures are able to reach each other'
      );

      if (!res.locals.conditions) {
        res.locals.conditions = [];
      }

      res.locals.conditions.push((parcel) => {
        return checkAreFiguresAbleToReachEachOther(parcel);
      });

      next();
    })();

    function checkAreFiguresAbleToReachEachOther(parcel) {
      const figureCoordsArray = calculateFigureCoordsArray(parcel);
      const height = parcel.length;
      const width = parcel[0].length;
      const firstCoord = figureCoordsArray.shift(); // mutating

      let isPossible = true;
      figureCoordsArray.forEach((coord) => {
        const grid = new PF.Grid(width, height);

        // define collidables
        parcel.forEach((row, y) => {
          row.forEach((figure, x) => {
            if (figure === 'tree') {
              grid.setWalkableAt(x, y, false);
            }
          });
        });

        const finder = new PF.AStarFinder({ allowDiagonal: false });
        const path = finder.findPath(
          firstCoord.x,
          firstCoord.y,
          coord.x,
          coord.y,
          grid
        );

        if (_.isEmpty(path)) {
          isPossible = false;
        }
      });

      debug('checkAreFiguresAbleToReachEachOther', isPossible);
      return isPossible;
    }

    function calculateFigureCoordsArray(parcel) {
      const figureCoordsArray = [];
      parcel.forEach((row, y) => {
        row.forEach((figure, x) => {
          if (figure !== 'empty' && figure !== 'tree') {
            figureCoordsArray.push({ x: x, y: y });
          }
        });
      });
      return figureCoordsArray;
    }
  };
};
